# Generated by Django 3.0.7 on 2020-08-02 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20200802_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='phone',
        ),
    ]
