# Generated by Django 3.0.7 on 2020-08-04 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_itembackgroup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemBackgroup',
            new_name='ItemBackgroud',
        ),
    ]
