# Generated by Django 3.0.7 on 2020-08-04 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20200804_1849'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemBackgroud',
        ),
    ]
